alter session set  "_oracle_script"=true;
CREATE USER main_manager IDENTIFIED BY "0000"  ;
GRANT GRANT ANY PRIVILEGE TO main_manager;
GRANT create table to main_manager;
GRANT REFERENCES ON USER1.Student TO main_manager;
GRANT REFERENCES ON USER1.Course TO main_manager;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'MANAGER';

SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'MANAGER';

GRANT CREATE SESSION TO MANAGER; -- Required to log in to the database
GRANT ALTER USER TO MANAGER;  

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'MANAGER';
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'MANAGER';
sqlplus MANAGER/1111@MANAGER_CONNECTION

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'USER1' AND PRIVILEGE = 'CREATE TABLE';

GRANT SELECT ON MAIN_MANAGER.REGISTER TO user1,user2;
